(lambda (run-test make-messenger control-src standard-src chain-src tree-src config-src ledger-src)
  (let* ((pass (lambda (x) (append "pass-" (symbol->string x))))
         (init (lambda (x) `(,x (,control-src ,(pass x)) "Installed control module")))
         (install (lambda (x) `(,(car x) (*call* ,(pass (car x)) ,(cadr x)) #t)))
         (setup (lambda (args)
                  (let ((journal-name (car args))
                        (obj-name (cadr args)))
                    `(,journal-name
                      (*call* ,(pass journal-name)
                              (lambda (root)
                                (let* ((std-node ((root 'get) '(control object standard)))
                                       (standard ((eval (byte-vector->expression (sync-car std-node))) std-node))
                                       (config-class ((root 'get) '(control class configuration)))
                                       (tree-class ((root 'get) '(control class tree)))
                                       (chain-class ((root 'get) '(control class chain)))
                                       (ledger-class ((root 'get) '(control class ledger)))
                                       (keys (crypto-generate (expression->byte-vector ,(pass journal-name))))
                                       (config-expr `((public ((window 10)
                                                               (public-key ,(car keys))))
                                                      (private ((secret-key ,(cdr keys))
                                                                (tree-class ,tree-class)
                                                                (chain-class ,chain-class)))))
                                       (config ((standard 'make) config-class `(,config-expr)))
                                       (ledger ((standard 'make) ledger-class `(,standard ,config)))
                                       (handler '(lambda (root query)
                                                   (let* ((node ((root 'get) `(control test ,(caar query))))
                                                          (obj ((eval (byte-vector->expression (sync-car node))) node))
                                                          (res (if (eq? (cadr (cadar query)) '*step-all-test*)
                                                                   (let loop ((sub ((obj 'step-generate))) (results '()))
                                                                     (if (null? sub) (reverse results)
                                                                         (let ((r (apply (obj (caar sub)) (cdar sub))))
                                                                           (loop (cdr sub) (cons r results)))))
                                                                   (let* ((proc (lambda (x) (eval x)))
                                                                          (args (map proc (cdr query))))
                                                                     (apply (obj (cadr (cadar query))) args)))))
                                                     ((root 'set!) `(control test ,(caar query)) (obj)) res))))
                                  ((root 'set!) '(control endpoint test) handler)
                                  ((root 'set!) '(control test ,obj-name) (ledger))))) #t))))
         (peer (lambda (name)
                 (let ((keys (crypto-generate (expression->byte-vector (pass name))))
                       (messenger (make-messenger name)))
                   `((information (lambda () (,messenger `(test ((ledger 'information))))))
                     ;; (public-key ,(car keys))
                     (synchronize (lambda (index) (,messenger `(test ((ledger 'synchronize) ,index)))))
                     (resolve (lambda (source target) (,messenger `(test ((ledger 'resolve) ',source ',target)))))))))
         (query (lambda (args)
                  (let ((journal-name (car args))
                        (query~ (cadr args))
                        (test (if (null? (cddr args)) #t (caddr args))))
                    `(,journal-name (test ,query~) ,test)))))
    (run-test
     (append
      (map init '(journal-1 journal-2 journal-3 journal-4 journal-5))
      (map install `((journal-1 (lambda (root)
                                  ((root 'set!) '(control class standard) ',standard-src)
                                  ((root 'set!) '(control object standard)
                                   (let ((init (caddr ',standard-src)))
                                     (((eval `(lambda* ,(cddadr init) ,@(cddr init))) ',standard-src))))))
                     (journal-2 (lambda (root)
                                  ((root 'set!) '(control class standard) ',standard-src)
                                  ((root 'set!) '(control object standard)
                                   (let ((init (caddr ',standard-src)))
                                     (((eval `(lambda* ,(cddadr init) ,@(cddr init))) ',standard-src))))))
                     (journal-3 (lambda (root)
                                  ((root 'set!) '(control class standard) ',standard-src)
                                  ((root 'set!) '(control object standard)
                                   (let ((init (caddr ',standard-src)))
                                     (((eval `(lambda* ,(cddadr init) ,@(cddr init))) ',standard-src))))))
                     (journal-4 (lambda (root)
                                  ((root 'set!) '(control class standard) ',standard-src)
                                  ((root 'set!) '(control object standard)
                                   (let ((init (caddr ',standard-src)))
                                     (((eval `(lambda* ,(cddadr init) ,@(cddr init))) ',standard-src))))))
                     (journal-5 (lambda (root)
                                  ((root 'set!) '(control class standard) ',standard-src)
                                  ((root 'set!) '(control object standard)
                                   (let ((init (caddr ',standard-src)))
                                     (((eval `(lambda* ,(cddadr init) ,@(cddr init))) ',standard-src))))))
                     (journal-1 (lambda (root) ((root 'set!) '(control class tree) ',tree-src)))
                     (journal-2 (lambda (root) ((root 'set!) '(control class tree) ',tree-src)))
                     (journal-3 (lambda (root) ((root 'set!) '(control class tree) ',tree-src)))
                     (journal-4 (lambda (root) ((root 'set!) '(control class tree) ',tree-src)))
                     (journal-5 (lambda (root) ((root 'set!) '(control class tree) ',tree-src)))
                     (journal-1 (lambda (root) ((root 'set!) '(control class chain) ',chain-src)))
                     (journal-2 (lambda (root) ((root 'set!) '(control class chain) ',chain-src)))
                     (journal-3 (lambda (root) ((root 'set!) '(control class chain) ',chain-src)))
                     (journal-4 (lambda (root) ((root 'set!) '(control class chain) ',chain-src)))
                     (journal-5 (lambda (root) ((root 'set!) '(control class chain) ',chain-src)))
                     (journal-1 (lambda (root) ((root 'set!) '(control class configuration) ',config-src)))
                     (journal-2 (lambda (root) ((root 'set!) '(control class configuration) ',config-src)))
                     (journal-3 (lambda (root) ((root 'set!) '(control class configuration) ',config-src)))
                     (journal-4 (lambda (root) ((root 'set!) '(control class configuration) ',config-src)))
                     (journal-5 (lambda (root) ((root 'set!) '(control class configuration) ',config-src)))
                     (journal-1 (lambda (root) ((root 'set!) '(control class ledger) ',ledger-src)))
                     (journal-2 (lambda (root) ((root 'set!) '(control class ledger) ',ledger-src)))
                     (journal-3 (lambda (root) ((root 'set!) '(control class ledger) ',ledger-src)))
                     (journal-4 (lambda (root) ((root 'set!) '(control class ledger) ',ledger-src)))
                     (journal-5 (lambda (root) ((root 'set!) '(control class ledger) ',ledger-src)))))

      (map setup '((journal-1 ledger) (journal-2 ledger) (journal-3 ledger) (journal-4 ledger) (journal-5 ledger)))
      (map query
           `((journal-1 ((ledger 'size)) 0)
             (journal-1 ((ledger '*step-all-test*)) '(1))
             (journal-1 ((ledger 'get) '((*state*))) '(directory ((*time* value)) #t))
             (journal-1 ((ledger 'set!) '((*state* do pin this)) "yes") #t)
             (journal-1 ((ledger 'set!) '((*state* do pin that)) "yes") #t)
             (journal-1 ((ledger 'set!) '((*state* do not pin)) "no") #t)
             (journal-1 ((ledger 'get) '((*state* do not pin))) "no")
             (journal-1 ((ledger 'get) '((*state* do pin))) '(directory ((this value) (that value)) #t))
             (journal-1 ((ledger '*step-all-test*)) '(2))
             (journal-1 ((ledger '*step-all-test*)) '(3))
             (journal-1 ((ledger 'get) '(-1 (*state* do pin this))) "yes")
             (journal-1 ((ledger 'get) '(-1 (*state* do pin that))) "yes")
             (journal-1 ((ledger 'pin!) '(2 (*state* do pin this))) #t)
             (journal-1 ((ledger 'pin!) '(2 (*state* do pin that))) #t)
             (journal-1 ((ledger 'get) '(2 (*state* do pin))) '(directory ((this value) (that value)) #t))
             (journal-1 ((ledger 'peer!) 'journal-2 ',(peer 'journal-2)) #t)
             (journal-1 ((ledger 'peers)) '(journal-2))
             (journal-1 ((ledger '*step-all-test*)) '(4 #t))
             (journal-2 ((ledger 'set!) '((*state* a b c)) 42) #t)
             (journal-2 ((ledger 'set!) '((*state* a b c*)) 43) #t)
             (journal-2 ((ledger '*step-all-test*)) '(1))
             (journal-2 ((ledger 'get) '(-1 (*state* a b c*))) 43)
             (journal-1 ((ledger '*step-all-test*)) '(5 #t))
             (journal-2 ((ledger '*step-all-test*)) '(2))
             (journal-1 ((ledger '*step-all-test*)) '(6 #t))
             (journal-2 ((ledger '*step-all-test*)) '(3))
             (journal-2 ((ledger 'pin!) '(2 (*state* a b c))) #t)
             (journal-1 ((ledger '*step-all-test*)) '(7 #t))
             (journal-2 ((ledger '*step-all-test*)) '(4))
             (journal-1 ((ledger '*step-all-test*)) '(8 #t))
             (journal-2 ((ledger '*step-all-test*)) '(5))
             (journal-2 ((ledger 'set!) '((*state* a b c)) 44) #t)
             (journal-1 ((ledger '*step-all-test*)) '(9 #t))
             (journal-2 ((ledger '*step-all-test*)) '(6))
             (journal-1 ((ledger 'get) '(-1 (*peer* journal-2 chain) -1 (*state* a b))) '(directory ((c value) (c* value)) #t))
             (journal-1 ((ledger 'get) '(-1 (*peer* journal-2 chain) -1 (*state* a b c))) 42)
             (journal-2 ((ledger 'peer!) 'journal-3 ',(peer 'journal-3)) #t)
             (journal-3 ((ledger 'peer!) 'journal-4 ',(peer 'journal-4)) #t)
             (journal-3 ((ledger 'peer!) 'journal-5 ',(peer 'journal-5)) #t)
             (journal-3 ((ledger 'set!) '((*state* d e f)) 64) #t)
             (journal-4 ((ledger 'set!) '((*state* g h i)) "hello") #t)
             (journal-5 ((ledger 'set!) '((*state* g h i)) "world") #t)
             (journal-1 ((ledger '*step-all-test*)) '(10 #t))
             (journal-2 ((ledger '*step-all-test*)) '(7 #t))
             (journal-3 ((ledger '*step-all-test*)) '(1 #t #t))
             (journal-4 ((ledger '*step-all-test*)) '(1))
             (journal-5 ((ledger '*step-all-test*)) '(1))
             (journal-1 ((ledger '*step-all-test*)) '(11 #t))
             (journal-2 ((ledger '*step-all-test*)) '(8 #t))
             (journal-3 ((ledger '*step-all-test*)) '(2 #t #t))
             (journal-4 ((ledger '*step-all-test*)) '(2))
             (journal-5 ((ledger '*step-all-test*)) '(2))
             (journal-1 ((ledger '*step-all-test*)) '(12 #t))
             (journal-2 ((ledger '*step-all-test*)) '(9 #t))
             (journal-3 ((ledger '*step-all-test*)) '(3 #t #t))
             (journal-4 ((ledger '*step-all-test*)) '(3))
             (journal-5 ((ledger '*step-all-test*)) '(3))
             (journal-2 ((ledger 'get) '(-1 (*peer* journal-3 chain) -1 (*state* d e f))) 64)
             (journal-1 ((ledger '*step-all-test*)) '(13 #t))
             (journal-2 ((ledger '*step-all-test*)) '(10 #t))
             (journal-3 ((ledger '*step-all-test*)) '(4 #t #t))
             (journal-4 ((ledger '*step-all-test*)) '(4))
             (journal-5 ((ledger '*step-all-test*)) '(4))
             (journal-1 ((ledger '*step-all-test*)) '(14 #t))
             (journal-2 ((ledger '*step-all-test*)) '(11 #t))
             (journal-3 ((ledger '*step-all-test*)) '(5 #t #t))
             (journal-4 ((ledger '*step-all-test*)) '(5))
             (journal-5 ((ledger '*step-all-test*)) '(5))
             (journal-1 ((ledger 'get) '(-1 (*peer* journal-2 chain) -1 (*peer* journal-3 chain) -1 (*state* d e f))) 64)
             (journal-1 ((ledger '*step-all-test*)) '(15 #t))
             (journal-2 ((ledger '*step-all-test*)) '(12 #t))
             (journal-3 ((ledger '*step-all-test*)) '(6 #t #t))
             (journal-4 ((ledger '*step-all-test*)) '(6))
             (journal-5 ((ledger '*step-all-test*)) '(6))
             (journal-1 ((ledger '*step-all-test*)) '(16 #t))
             (journal-2 ((ledger '*step-all-test*)) '(13 #t))
             (journal-3 ((ledger '*step-all-test*)) '(7 #t #t))
             (journal-4 ((ledger '*step-all-test*)) '(7))
             (journal-5 ((ledger '*step-all-test*)) '(7))
             (journal-1 ((ledger 'get) '(-1 (*peer* journal-2 chain) -1
                                            (*peer* journal-3 chain) -1
                                            (*peer* journal-4 chain) -1
                                            (*state* g h i))) "hello")
             (journal-1 ((ledger 'get) '(-1 (*peer* journal-2 chain) -1
                                            (*peer* journal-3 chain) -1
                                            (*peer* journal-5 chain) -1
                                            (*state* g h i)) #t) (lambda (x) (equal? (cadr (assoc 'content x)) "world")))

             (journal-1 ((ledger 'get) '(2 (*state* do pin))) '(directory ((this value) (that value)) #t))
             (journal-1 ((ledger 'get) '(2 (*state* do pin this))) "yes")
             (journal-1 ((ledger 'get) '(2 (*state* do pin that))) "yes")
             (journal-1 ((ledger 'get) '(2 (*state* do not pin))) '(unknown))
             (journal-1 ((ledger 'unpin!) '(2 (*state* do pin that))) #t)
             (journal-1 ((ledger 'get) '(2 (*state* do pin this))) "yes")
             (journal-1 ((ledger 'get) '(2 (*state* do pin that))) '(unknown))
             (journal-1 ((ledger 'get) '(14 (*peer* journal-2 chain) -1 (*state* a b c))) 44)
             (journal-1 ((ledger 'get) '(14 (*peer* journal-2 chain) -6 (*state* a b c))) 42)
             (journal-1 ((ledger '*update*) 'ledger (lambda (obj) obj)) 'self)
             (journal-1 ((ledger '*update*) 'config (lambda (obj) obj)) 'self)
             (journal-1 ((ledger '*update*) 'tree (lambda (obj) obj)) 'self)
             (journal-1 ((ledger '*update*) 'chain (lambda (obj) obj)) 'self)))))))
