(lambda (run-test make-messenger control-src standard-src)
  (let* ((pass (lambda (x) (append "pass-" (symbol->string x))))
         (init (lambda (x) `(,x (,control-src ,(pass x)) "Installed control module")))
         (install (lambda (x) `(,(car x) (*call* ,(pass (car x)) ,(cadr x)) #t)))
         (query (lambda (x)
                  `(,(car x)
                    (*call* ,(pass (car x))
                            (lambda (root)
                              (let* ((std-node ((root 'get) '(control object standard)))
                                     (std ((eval (byte-vector->expression (sync-car std-node))) std-node)))
                                ,(cadr x))))
                    ,@(cddr x)))))
    (run-test
     (append
      (map init '(journal))
      (map install `((journal (lambda (root)
                                ((root 'set!) '(control class standard) ',standard-src)
                                ((root 'set!) '(control object standard)
                                 (let ((init (caddr ',standard-src)))
                                   (((eval `(lambda* ,(cddadr init) ,@(cddr init))) ',standard-src)))))
                              "Installed standard library")))
      (map query
           `((journal ((root 'set!) '(control test source)
                       ((std 'dump) std)) #t)
             (journal ((root 'set!) '(control test stateful)
                       (((std 'make) '(define-class (foo)
                                        (define-method (add self x) (+ x 1))
                                        (define-method (fact self x (result 1))
                                          (if (< x 1) result
                                              ((self 'fact) (- x 1) (* result x))))
                                        (define-method (state-get self)
                                          (byte-vector->expression (sync-cdr (self))))
                                        (define-method (state-set! self x)
                                          (set! (self) (sync-cons (sync-car (self))
                                                                  (expression->byte-vector x)))))))) #t)
             (journal (let ((object ((std 'load) ((root 'get) '(control test stateful)))))
                        ((object 'add) 1)) 2)
             (journal (let ((object ((std 'load) ((root 'get) '(control test stateful)))))
                        ((object 'fact) 4)) (* 4 3 2 1))
             (journal (let ((object ((std 'load) ((root 'get) '(control test stateful)))))
                        ((object 'state-set!) "hello, world!")
                        ((root 'set!) '(control test stateful) ((std 'dump) object))) #t)
             (journal (let ((object ((std 'load) ((root 'get) '(control test stateful)))))
                        ((object 'state-get))) "hello, world!")
             (journal (let* ((object ((std 'load) ((root 'get) '(control test stateful))))
                             (query '(lambda (node)
                                       (let ((object ((eval (byte-vector->expression (sync-car node))) node)))
                                         ((object 'state-set!) 5)
                                         ((object 'state-get)))))
                             (serialized ((std 'serialize) (object) query))
                             (deserialized ((std 'deserialize) serialized)))
                        ((eval query) deserialized)) 5)
             (journal (let ((object-1 ((std 'make) '(define-class (class-1)
                                                       (define-method (get self ~index)
                                                         (self '(1)))
                                                       (define-method (set! self ~index value)
                                                         (set! (self '(1)) value))
                                                       (define-method (slice! self ~index) #t)
                                                       (define-method (prune! self ~index) #t))))
                            (object-2 ((std 'make) '(define-class (class-2)
                                                       (define-method (*init* self)
                                                         (set! (self '(1)) (sync-cons (sync-null) (sync-null))))
                                                       (define-method (get self index)
                                                         (self `(1 ,index)))
                                                       (define-method (set! self index value)
                                                         (set! (self `(1 ,index)) value))
                                                       (define-method (slice! self index)
                                                         (let ((other (if (= index 0) 1 0)))
                                                           (set! (self `(1 ,other)) (sync-cut (self `(1 ,other))))))
                                                       (define-method (prune! self index)
                                                         (set! (self `(1 ,index)) (sync-cut (self `(1 ,index))))))))
                            (object-3 ((std 'make) '(define-class (class-3)
                                                      (define-method (*init* self)
                                                        (set! (self '(1)) (expression->byte-vector 0)))
                                                       (define-method (get self ~key)
                                                         (byte-vector->expression (self '(1))))
                                                       (define-method (set! self ~key value)
                                                         (set! (self '(1)) (expression->byte-vector value)))
                                                      (define-method (increment! self)
                                                        (let ((previous (byte-vector->expression (self '(1)))))
                                                          (set! (self '(1)) (expression->byte-vector (+ previous 1)))))))))
                        ((object-2 'set!) 1 (object-3))
                        ((object-1 'set!) "some path" (object-2))
                        ((root 'set!) '(control test deep) ((std 'dump) object-1))) #t)
             (journal (let ((object ((std 'load) ((root 'get) '(control test deep)))))
                        ((std 'deep-get) object '("some path" 1 #f))) 0)
             (journal (let ((object ((std 'load) ((root 'get) '(control test deep)))))
                        ((std 'deep-set!) object '("some path" 1 #f) 4)
                        ((std 'deep-get) object '("some path" 1 #f))) 4)
             (journal (let ((object ((std 'load) ((root 'get) '(control test deep)))))
                        ((std 'deep-slice!) object '("some path" 1))) #t)
             (journal (let ((object ((std 'load) ((root 'get) '(control test deep)))))
                        ((std 'deep-prune!) object '("some path" 1))) #t)
             (journal (let ((object ((std 'load) ((root 'get) '(control test deep)))))
                        ((std 'deep-copy!) object '("some path" 1) '("some path" 0))) #t)
             (journal (let ((object ((std 'load) ((root 'get) '(control test deep)))))
                        ((std 'deep-merge!) object object)) #t)
             (journal (let ((object ((std 'load) ((root 'get) '(control test deep)))))
                        ((std 'deep-call!) object '("some path" 1) (lambda (obj) ((obj 'increment!))))
                        ((std 'deep-call!) object '("some path" 1) (lambda (obj) ((obj 'increment!))))
                        ((std 'deep-call!) object '("some path" 1) (lambda (obj) ((obj 'get) #f)))) 2)
             ))
      ))))
