(lambda (run-test make-messenger control-src standard-src linear-chain-src log-chain-src)
  (let* ((pass (lambda (x) (append "pass-" (symbol->string x))))
         (init (lambda (x) `(,x (,control-src ,(pass x)) "Installed control module")))
         (install (lambda (x) `(,(car x) (*call* ,(pass (car x)) ,(cadr x)) #t)))
         (query (lambda (x)
                  `(,(car x)
                    (*call* ,(pass (car x))
                            (lambda (root)
                              (let* ((std-node ((root 'get) '(control object standard)))
                                     (std ((eval (byte-vector->expression (sync-car std-node))) std-node)))
                                ,(cadr x))))
                    ,@(cddr x))))
         (queries (lambda (chain)
                    (map query
                         `((journal (let ((chain ((std 'make) ((root 'get) '(control class ,chain)))))
                                      ((root 'set!) '(control test chain-1) ((std 'dump) chain))) #t)
                           (journal (let ((chain ((std 'load) ((root 'get) '(control test chain-1)))))
                                      ((chain 'size))) 0)
                           (journal (let ((chain ((std 'load) ((root 'get) '(control test chain-1)))))
                                      ((chain 'push!) (expression->byte-vector "hello"))
                                      ((chain 'push!) (expression->byte-vector ","))
                                      ((chain 'push!) (expression->byte-vector "world"))
                                      ((chain 'push!) (expression->byte-vector "!"))
                                      ((root 'set!) '(control test chain-1) (chain))) #t)
                           (journal (let ((chain ((std 'load) ((root 'get) '(control test chain-1)))))
                                      (list (byte-vector->expression ((chain 'get) 0))
                                            (byte-vector->expression ((chain 'get) 1))
                                            (byte-vector->expression ((chain 'get) 2))
                                            (byte-vector->expression ((chain 'get) 3))
                                            )) '("hello" "," "world" "!"))
                           (journal (let ((chain ((std 'load) ((root 'get) '(control test chain-1)))))
                                      ((chain 'set!) 1 (expression->byte-vector ":"))
                                      (byte-vector->expression ((chain 'get) 1))) ":")
                           (journal (let ((chain ((std 'load) ((root 'get) '(control test chain-1)))))
                                      ((chain 'slice!) 1)
                                      (byte-vector->expression ((chain 'get) 1))) ",")
                           (journal (let ((chain ((std 'load) ((root 'get) '(control test chain-1)))))
                                      ((chain 'prune!) 1)
                                      (byte-vector->expression ((chain 'get) -1))) "!")
                           (journal (let ((chain ((std 'load) ((root 'get) '(control test chain-1)))))
                                      ((chain 'truncate!) 1)
                                      (byte-vector->expression ((chain 'get) -1))) "!")
                           (journal (let ((chain-1 ((std 'load) ((root 'get) '(control test chain-1))))
                                          (chain-2 ((std 'load) ((root 'get) '(control test chain-1))))
                                          (chain-3 ((std 'load) ((root 'get) '(control test chain-1)))))
                                      ((chain-2 'push!) (expression->byte-vector "this"))
                                      ((chain-2 'push!) (expression->byte-vector "is"))
                                      ((chain-3 'push!) (expression->byte-vector "this"))
                                      ((chain-3 'push!) (expression->byte-vector "is"))
                                      ((chain-3 'push!) (expression->byte-vector "a"))
                                      ((chain-3 'push!) (expression->byte-vector "somewhat"))
                                      ((chain-3 'push!) (expression->byte-vector "longer"))
                                      ((chain-3 'push!) (expression->byte-vector "chain"))
                                      (and (equal? ((chain-1 'digest)) ((chain-2 'digest) -3))
                                           (equal? ((chain-1 'digest)) ((chain-3 'digest) -7)))) #t)
                           (journal (let ((chain ((std 'make) ((root 'get) '(control class ,chain)))))
                                      (let loop ((i 100))
                                        (if (= i 0) ((chain 'size))
                                            (begin ((chain 'push!) #u())
                                                   (loop (- i 1)))))) 100)
                           (journal (let* ((size 100)
                                           (chain ((std 'make) ((root 'get) '(control class ,chain))))
                                           (digests-1 (let loop ((i 0) (digests '()))
                                                        (if (= i size) (reverse digests)
                                                            (begin ((chain 'push!) (sync-null))
                                                                   (loop (+ i 1) (cons ((chain 'digest)) digests))))))
                                           (digests-2 (let loop ((i 0) (digests '()))
                                                        (if (= i size) (reverse digests)
                                                            (loop (+ i 1) (cons ((chain 'digest) i) digests))))))
                                      (equal? digests-1 digests-2)) #t)
                           )))))
    (run-test
     (append
      (map init '(journal))
      (map install `((journal (lambda (root)
                                ((root 'set!) '(control class standard) ',standard-src)
                                ((root 'set!) '(control object standard)
                                 (let ((init (caddr ',standard-src)))
                                   (((eval `(lambda* ,(cddadr init) ,@(cddr init))) ',standard-src))))))
                     (journal (lambda (root) ((root 'set!) '(control class linear-chain) ',linear-chain-src)))
                     (journal (lambda (root) ((root 'set!) '(control class log-chain) ',log-chain-src)))))
      (queries 'linear-chain)
      (queries 'log-chain)))))
