location = / {
    try_files /index.html =404;
}

location = /webdav-guide {
    try_files /webdav-guide.html =404;
}

location /interface {
    proxy_pass http://journal/interface;
}

location /api/ {
    proxy_pass http://gateway;
}

location /auth/ {
    proxy_pass http://gateway;
}

location = /gateway {
    proxy_pass http://gateway/;
}

location = /gateway-logo.png {
    proxy_pass http://gateway/gateway-logo.png;
}

location = /docs {
    proxy_pass http://gateway/docs;
}

location = /healthz {
    proxy_pass http://gateway/healthz;
}

location = /readyz {
    proxy_pass http://gateway/readyz;
}

location = /metrics {
    proxy_pass http://gateway/metrics;
}

location /explorer {
    proxy_pass http://explorer/;
}

location /workbench {
    proxy_pass http://workbench/;
}

location = /webdav {
    proxy_pass http://file-system:8080;
}

location /webdav/ {
    proxy_pass http://file-system:8080;
}
