networks:
 docker:
    name: docker

services:
  journal:
    image: ghcr.io/sandialabs/sync-services/general:1.1.1
    container_name: journal
    networks:
      - docker
    environment:
      SECRET: ${SECRET}
      PERIOD: ${PERIOD:-2}
      WINDOW: ${WINDOW:-1024}
      RUST_LOG: ${RUST_LOG:-INFO}
    volumes:
      - database:/srv/database

  explorer:
    image: ghcr.io/sandialabs/sync-services/explorer:1.0.1
    container_name: explorer
    networks:
      - docker
    environment:
      SYNC_EXPLORER_ENDPOINT: /api/v1

  workbench:
    image: ghcr.io/sandialabs/sync-services/workbench:1.0.1
    container_name: workbench
    networks:
      - docker
    environment:
      SYNC_WORKBENCH_ENDPOINT: /interface

  gateway:
    image: ghcr.io/sandialabs/sync-services/gateway:1.0.0
    container_name: gateway
    networks:
      - docker
    depends_on:
      - journal
    environment:
      HOST: 0.0.0.0
      PORT: 80
      JOURNAL_JSON_ENDPOINT: http://journal/interface/json
      JOURNAL_LISP_ENDPOINT: http://journal/interface
      ALLOW_ADMIN_ROUTES: "1"

  router:
    image: ghcr.io/sandialabs/sync-services/router:1.1.0
    container_name: router
    environment:
      TLS_CERT_FILE: ${TLS_CERT_FILE:-/etc/nginx/certs/tls.crt}
      TLS_KEY_FILE: ${TLS_KEY_FILE:-/etc/nginx/certs/tls.key}
    volumes:
      - ${TLS_CERT_HOST_PATH:-./tls/tls.crt}:/etc/nginx/certs/tls.crt:ro
      - ${TLS_KEY_HOST_PATH:-./tls/tls.key}:/etc/nginx/certs/tls.key:ro
    depends_on:
      - journal
      - explorer
      - workbench
      - gateway
    networks:
      - docker
    ports:
      - "${PORT:-8192}:80"
      - "${HTTPS_PORT:-443}:443"

volumes:
  database:
