server {
    listen 80;

    location /interface {
        proxy_pass http://journal.docker/interface;
    }

    location = /gateway {
        return 301 /gateway/;
    }

    location /gateway/ {
        proxy_pass http://gateway.docker/;
    }

    location /api/ {
        proxy_pass http://gateway.docker;
    }

    location = /docs {
        proxy_pass http://gateway.docker/docs;
    }

    location = /api/docs {
        proxy_pass http://gateway.docker/api/docs;
    }

    location = /healthz {
        proxy_pass http://gateway.docker/healthz;
    }

    location = /readyz {
        proxy_pass http://gateway.docker/readyz;
    }

    location /explorer {
        proxy_pass http://explorer.docker/;
    }

    location /workbench {
        proxy_pass http://workbench.docker/;
    }
}
