(lambda (assertions-src standard-src chain-src tree-src ledger-src document-src)

  (eval assertions-src)

  (define standard
    (let ((init (caddr standard-src)))
      (sync-eval ((eval `(lambda* ,(cddadr init) ,@(cddr init))) standard-src) #f)))

  (define chain-cls chain-src)
  (define tree-cls tree-src)
  (define ledger-cls ledger-src)
  (define document-cls document-src)

  (define (make-ledger name)
    (let* ((keys (crypto-generate (expression->byte-vector name)))
           (config-expr `((public ((window 4)
                                   (public-key ,(car keys))))
                          (private ((secret-key ,(cdr keys)))))))
      (assert ((standard 'init) ledger-cls (standard) config-expr tree-cls chain-cls document-cls)
              sync-node?)))

  (define ledger-1 (sync-eval (make-ledger 'ledger-1) #f))
  (define ledger-2 (sync-eval (make-ledger 'ledger-2) #f))
  (define ledger-3 (sync-eval (make-ledger 'ledger-3) #f))
  (define ledger-4 (sync-eval (make-ledger 'ledger-4) #f))
  (define ledger-5 (sync-eval (make-ledger 'ledger-5) #f))
  (define ledger-flat (sync-eval (make-ledger 'ledger-flat) #f))
  (define ledger-pin-1 (sync-eval (make-ledger 'ledger-pin-1) #f))
  (define ledger-pin-2 (sync-eval (make-ledger 'ledger-pin-2) #f))

  (define (step-all! ledger)
    (let loop ((names (map car ((ledger 'config) '(private bridge))))
               (result (list ((ledger 'step!) (system-time-unix)))))
      (if (null? names) (reverse result)
          (let* ((name (car names))
                 (peer (eval name))
                 (value ((standard 'deep-get) ((ledger '~field!) 'stage) `((*bridge* ,name chain))))
                 (index (if (sync-node? value) (- (((sync-eval value #f) 'size)) 1) -1))
                 (response ((peer 'synchronize) index)))
            (loop (cdr names)
                  (cons ((ledger 'bridge-synchronize!) name index response) result))))))

  (define (bridge! ledger peer-name)
    (let ((peer (eval peer-name)))
      ((ledger 'bridge!) peer-name `((interface ,peer-name) (policy ((publish push) (subscribe pull))) (role #f) (remote-name ,peer-name)) ((peer 'info)))))

  (define (serialize-full node)
    ((standard 'serialize) node
     '(lambda (x)
        (let loop ((x x))
          (if (not (sync-pair? x)) x
              (sync-cons (loop (sync-car x)) (loop (sync-cdr x))))))))

  (define (internal->flat path)
    (cond ((null? path) '())
          ((and (integer? (car path)) (not (null? (cdr path))) (pair? (cadr path)))
           (let ((index (car path))
                 (segment (cadr path))
                 (tail (cddr path)))
             (cond ((eq? (car segment) '*bridge*)
                    (append `(,index *bridge* ,(cadr segment)) (internal->flat tail)))
                   (else (append `(,index ,@segment) (internal->flat tail))))))
          (else path)))

  (define* (fetch ledger path index)
    (let* ((path~ ((ledger '~path-normalize) path #f #f))
           (name (cadadr path~))
           (peer (eval name))
           (local-index (car path~))
           (local-chain ((ledger 'resolve) '()))
           (local-chain (if index (((sync-eval local-chain #f) 'previous) index) local-chain))
           (remote-chain ((standard 'deep-get) local-chain `(,local-index (*bridge* ,name chain))))
           (remote-index (- (((sync-eval remote-chain #f) 'size)) 1))
           (remote-path (internal->flat (list-tail path~ 2)))
           (response (trace-ledger peer remote-index remote-path))
           (head ((standard 'deserialize) response))
           (prefix (reverse (list-tail (reverse path~) (- (length path~) 2))))
           (merged ((standard 'deep-merge!) head remote-chain)))
      (if (not (equal? (sync-digest remote-chain) (sync-digest head)))
          (error 'integrity-error "Remote chain does not match local chain head for path: ~S" path)
          ((standard 'deep-set!) local-chain prefix merged))))

  (define (bridge-path? path)
    (let ((tokens (if (and (pair? path) (integer? (car path))) (cdr path) path)))
      (and (pair? tokens) (eq? (car tokens) '*bridge*))))

  (define (get-expr ledger path)
    ((ledger 'get) path #f #t))

  (define (get-expr+meta ledger path)
    ((ledger 'get) path #t #t))

  (define (set-expr! ledger path value)
    ((ledger 'set!) path value '() #t))

  (define (set-expr+meta! ledger path value meta)
    ((ledger 'set!) path value meta #t))

  (define* (resolve ledger path pinned? proof?)
    (let ((attempt ((ledger 'resolve) path #f #f #f #f #t)))
      (cond ((not (equal? attempt '(unknown))) ((ledger 'resolve) path pinned? proof? #f #f #t))
            ((not (bridge-path? path)) attempt)
            (else ((ledger 'resolve) path pinned? proof? (fetch ledger path) #f #t)))))

  (define (trace-ledger ledger index path)
    (let* ((path~ (cond ((null? path) `(,index))
                        ((>= (car path) 0) path)
                        ((>= index 0) (cons (+ (+ index 1) (car path)) (cdr path)))
                        (else (cons (+ index (car path) 1) (cdr path)))))
           (attempt ((ledger 'resolve) path~)))
      (cond ((not (equal? attempt '(unknown))) ((ledger 'trace) index path))
            ((not (bridge-path? path~))
             (error 'path-error "Cannot trace unknown path: ~S" path))
            (else ((ledger 'trace) index path (fetch ledger path~ index))))))

  (define (pin! ledger path)
    (let ((attempt ((ledger 'resolve) path)))
      (cond ((not (equal? attempt '(unknown))) ((ledger 'pin!) path #f))
            ((not (bridge-path? path))
             (error 'path-error "Cannot pin unknown content at path: ~S" path))
            (else
             (let* ((merged (fetch ledger path))
                    (response ((ledger 'trace) -1 path merged)))
               ((ledger 'pin!) path response))))))

  (define (pin-trace! ledger path)
    (let ((attempt ((ledger 'resolve) path)))
      (cond ((not (equal? attempt '(unknown))) ((ledger 'pin!) path #f))
            ((not (bridge-path? path))
             (error 'path-error "Cannot pin unknown content at path: ~S" path))
            (else
             (let* ((merged (fetch ledger path))
                    (response ((ledger 'trace) -1 path merged)))
               ((ledger 'pin!) path response))))))

  (assert (bridge! ledger-pin-1 'ledger-pin-2) #t)
  (assert (set-expr! ledger-pin-2 '(*state* sib a) "a") #t)
  (assert (set-expr! ledger-pin-2 '(*state* sib b) "b") #t)
  (assert (step-all! ledger-pin-2) '(1))
  (assert (step-all! ledger-pin-1) '(1 #t))
  (assert (step-all! ledger-pin-1) '(2 #t))
  (assert (pin-trace! ledger-pin-1 '(-1 *bridge* ledger-pin-2 *state* sib a)) #t)
  (assert (resolve ledger-pin-1 '(-1 *bridge* ledger-pin-2 *state* sib a) #t #f)
          (lambda (x) (and (equal? (cadr (assoc 'content x)) "a")
                           (equal? (cadr (assoc 'pinned? x)) #t))))
  (assert (resolve ledger-pin-1 '(-1 *bridge* ledger-pin-2 *state* sib b) #t #f)
          (lambda (x) (and (equal? (cadr (assoc 'content x)) "b")
                           (equal? (cadr (assoc 'pinned? x)) #f))))
  (assert ((ledger-pin-1 'unpin!) '(-1 *bridge* ledger-pin-2 *state* sib a)) #t)
  (assert (resolve ledger-pin-1 '(-1 *bridge* ledger-pin-2 *state* sib a) #t #f)
          (lambda (x) (and (equal? (cadr (assoc 'content x)) "a")
                           (equal? (cadr (assoc 'pinned? x)) #f))))
  (assert (pin-trace! ledger-pin-1 '(-1 *bridge* ledger-pin-2 *state* sib a)) #t)
  (assert (pin-trace! ledger-pin-1 '(-1 *bridge* ledger-pin-2 *state* sib b)) #t)
  (assert ((ledger-pin-1 'unpin!) '(-1 *bridge* ledger-pin-2 *state* sib a)) #t)
  (assert (resolve ledger-pin-1 '(-1 *bridge* ledger-pin-2 *state* sib a) #t #f)
          (lambda (x) (and (equal? (cadr (assoc 'content x)) "a")
                           (equal? (cadr (assoc 'pinned? x)) #f))))
  (assert (resolve ledger-pin-1 '(-1 *bridge* ledger-pin-2 *state* sib b) #t #f)
          (lambda (x) (and (equal? (cadr (assoc 'content x)) "b")
                           (equal? (cadr (assoc 'pinned? x)) #t))))

  (assert ((ledger-1 'config)) (lambda (x) (and (list? x) (not (null? x)))))

  (assert ((ledger-1 'size)) 0)

  (assert (step-all! ledger-1) '(1))

  (assert (step-all! ledger-flat) '(1))
  (assert (set-expr! ledger-flat '(*state* flat alpha) "flat") #t)
  (assert (get-expr ledger-flat '(*state* flat alpha)) "flat")
  (assert ((ledger-flat 'get) '(*transition* operation)) '((path (*state* flat alpha)) (value "flat") (expression? #t)))
  (assert ((ledger-flat 'set!) '(*state* flat bytes) #u(1 2 3)) #t)
  (assert ((ledger-flat 'get) '(*state* flat bytes)) #u(1 2 3))
  (assert (catch #t
                 (lambda () ((ledger-flat 'set!) '(*state* flat rejected) "not bytes") 'no-error)
                 (lambda args (car args)))
          'value-error)
  (assert (step-all! ledger-flat) '(2))
  (assert ((ledger-flat 'resolve) '(*state* flat alpha) #f #f #f #f #t) "flat")
  (assert ((ledger-flat 'resolve) '(-1 *state* flat alpha) #f #f #f #f #t) "flat")
  (assert ((ledger-flat 'resolve) '(-1 *state* flat bytes)) #u(1 2 3))
  (assert (catch #t
                 (lambda () ((ledger-flat 'get) '((*state* flat alpha))) 'no-error)
                 (lambda args (car args)))
          'path-error)

  (assert ((ledger-1 'get) '(*state*)) '(directory ((*time* value)) #t))

  (assert (set-expr! ledger-1 '(*state* do pin this) "yes") #t)
  (assert (set-expr! ledger-1 '(*state* do pin that) "yes") #t)
  (assert (set-expr! ledger-1 '(*state* do not pin) "no") #t)
  (assert ((ledger-1 'set-batch!)
           '((*state* batch alpha)
             (*state* batch beta))
           '("a" "b")
           '(((alpha ((kind "plain"))))
             ((beta #f)))
           #t) #t)
  (assert (get-expr ledger-1 '(*state* do not pin)) "no")
  (assert ((ledger-1 'get) '(*state* do pin)) '(directory ((this value) (that value)) #t))
  (assert (get-expr ledger-1 '(*state* batch alpha)) "a")
  (assert (get-expr ledger-1 '(*state* batch beta)) "b")
  (assert (get-expr+meta ledger-1 '(*state* batch alpha))
          '((content "a") (meta ((alpha ((kind "plain")))))))
  (assert (get-expr+meta ledger-1 '(*state* batch beta))
          '((content "b") (meta ((beta #f)))))

  (assert ((ledger-1 'get) '(*transition* operation)) '((path (*state* batch beta)) (value "b") (expression? #t) (meta ((beta #f)))))
  (assert ((ledger-1 'get) '(*transition* previous operation))
          '((path (*state* batch alpha)) (value "a") (expression? #t) (meta ((alpha ((kind "plain")))))))
  (assert ((ledger-1 'get) '(*transition* previous previous operation)) '((path (*state* do not pin)) (value "no") (expression? #t)))

  (assert (step-all! ledger-1) '(2))

  (assert ((ledger-1 'get) '(*transition*)) '(nothing))

  (assert ((ledger-1 'resolve) '(-1 *transition* operation)) `((path (*state* *time*))
                                                                 (value ,((ledger-1 'resolve) '(-1 *state* *time*)))))
  (assert ((ledger-1 'resolve) '(-1 *transition* previous operation))
          '((path (*state* batch beta)) (value "b") (expression? #t) (meta ((beta #f)))))
  (assert ((ledger-1 'resolve) '(-1 *transition* previous previous operation))
          '((path (*state* batch alpha)) (value "a") (expression? #t) (meta ((alpha ((kind "plain")))))))

  (assert (resolve ledger-1 '(-1 *state* do pin this) #f #f) "yes")
  (assert (resolve ledger-1 '(-1 *state* do pin that) #f #f) "yes")

  (assert (pin! ledger-1 '(1 *state* do pin this)) #t)
  (assert (pin! ledger-1 '(1 *state* do pin that)) #t)

  (assert (resolve ledger-1 '(1 *state* do pin) #f #f)
          '(directory ((this value) (that value)) #t))

  (assert (bridge! ledger-1 'ledger-2) #t)
  (assert (step-all! ledger-1) (lambda (x) (and (list? x) (= (car x) 2))))

  (assert (set-expr! ledger-2 '(*state* a b c) 42) #t)
  (assert (set-expr! ledger-2 '(*state* a b c*) 43) #t)
  (assert (step-all! ledger-2) '(1))
  (assert (resolve ledger-2 '(-1 *state* a b c*) #f #f) 43)
  (assert ((ledger-2 'resolve) '(*state* a b c*) #f #f #f #f #t) 43)

  (assert (step-all! ledger-1) (lambda (x) (and (list? x) (= (car x) 3))))
  (assert (step-all! ledger-1) (lambda (x) (and (list? x) (= (car x) 4))))

  (assert ((ledger-1 'resolve) '(-1 *transition* previous previous operation))
          (lambda (x) (and (equal? (cadr (assoc 'path x)) '(*bridge* ledger-2))
                           (equal? (cadr (assoc 'valid? (cadr (assoc 'value x)))) #t)
                           (integer? (cadr (assoc 'index (cadr (assoc 'value x))))))))

  (assert (resolve ledger-1 '(-1 *bridge*) #f #f)
          '(directory ((ledger-2 directory)) #t))

  (assert (resolve ledger-1 '(-1 *bridge* ledger-2 *state* a b) #f #f)
          '(directory ((c value) (c* value)) #t))

  (assert (resolve ledger-1 '(-1 *bridge* ledger-2 *state* a b c) #f #f)
          42)

  (assert (pin-trace! ledger-1 '(-1 *bridge* ledger-2 *state* a b c)) #t)

  (assert (resolve ledger-1 '(-1 *bridge* ledger-2 *state* a b c) #t #f)
          (lambda (x) (and (equal? (cadr (assoc 'content x)) 42)
                           (equal? (cadr (assoc 'pinned? x)) #t))))
  (assert (resolve ledger-1 '(-1 *bridge* ledger-2 *state* a b c*) #t #f)
          (lambda (x) (and (equal? (cadr (assoc 'content x)) 43)
                           (equal? (cadr (assoc 'pinned? x)) #f))))
  (assert ((ledger-1 'unpin!) '(-1 *bridge* ledger-2 *state* a b c)) #t)
  (assert (resolve ledger-1 '(-1 *bridge* ledger-2 *state* a b c) #t #f)
          (lambda (x) (and (equal? (cadr (assoc 'content x)) 42)
                           (equal? (cadr (assoc 'pinned? x)) #f))))
  (assert (pin-trace! ledger-1 '(-1 *bridge* ledger-2 *state* a b c)) #t)
  (assert (pin-trace! ledger-1 '(-1 *bridge* ledger-2 *state* a b c*)) #t)
  (assert ((ledger-1 'unpin!) '(-1 *bridge* ledger-2 *state* a b c)) #t)
  (assert (resolve ledger-1 '(-1 *bridge* ledger-2 *state* a b c) #t #f)
          (lambda (x) (and (equal? (cadr (assoc 'content x)) 42)
                           (equal? (cadr (assoc 'pinned? x)) #f))))
  (assert (resolve ledger-1 '(-1 *bridge* ledger-2 *state* a b c*) #t #f)
          (lambda (x) (and (equal? (cadr (assoc 'content x)) 43)
                           (equal? (cadr (assoc 'pinned? x)) #t))))
  (assert ((ledger-1 'unpin!) '(-1 *bridge* ledger-2 *state* a b c*)) #t)
  (assert (pin-trace! ledger-1 '(-1 *bridge* ledger-2 *state* a b)) #t)
  (assert (resolve ledger-1 '(-1 *bridge* ledger-2 *state* a b) #t #f)
          (lambda (x) (and (equal? (cadr (assoc 'content x)) '(directory ((c value) (c* value)) #t))
                           (equal? (cadr (assoc 'pinned? x)) #t))))
  (assert (resolve ledger-1 '(-1 *bridge* ledger-2 *state* a b c) #t #f)
          (lambda (x) (and (equal? (cadr (assoc 'content x)) 42)
                           (equal? (cadr (assoc 'pinned? x)) #f))))
  (assert (resolve ledger-1 '(-1 *bridge* ledger-2 *state* a b c*) #t #f)
          (lambda (x) (and (equal? (cadr (assoc 'content x)) 43)
                           (equal? (cadr (assoc 'pinned? x)) #f))))

  (assert (bridge! ledger-2 'ledger-3) #t)
  (assert (bridge! ledger-3 'ledger-4) #t)
  (assert (bridge! ledger-3 'ledger-5) #t)

  (assert (set-expr! ledger-3 '(*state* d e f) 64) #t)
  (assert (set-expr! ledger-4 '(*state* g h i) "hello") #t)
  (assert (set-expr! ledger-5 '(*state* g h i) "world") #t)

  (assert (step-all! ledger-3) (lambda (x) (and (list? x) (= (car x) 1))))
  (assert (step-all! ledger-4) '(1))
  (assert (step-all! ledger-5) '(1))

  (assert (step-all! ledger-2) '(1 #t))
  (assert (step-all! ledger-1) '(4 #t))

  (assert (step-all! ledger-2) '(2 #t))
  (assert (step-all! ledger-1) '(4 #t))

  (assert (resolve ledger-2 '(-1 *bridge* ledger-3 *state* d e f) #f #f) 64)

  (assert (step-all! ledger-2) '(2 #t))
  (assert (step-all! ledger-1) '(5 #t))

  (assert (resolve ledger-1 '(-1 *bridge* ledger-2 -1
                                 *bridge* ledger-3 *state* d e f) #f #f)
          64)

  (assert (step-all! ledger-1) '(5 #t))
  (assert (step-all! ledger-2) '(2 #t))
  (assert (step-all! ledger-3) '(2 #t #t))
  (assert (step-all! ledger-4) '(1))
  (assert (step-all! ledger-5) '(1))

  (assert (step-all! ledger-1) '(5 #t))
  (assert (step-all! ledger-2) '(2 #t))
  (assert (step-all! ledger-3) '(3 #t #t))
  (assert (step-all! ledger-4) '(1))
  (assert (step-all! ledger-5) '(1))

  (assert (step-all! ledger-1) '(5 #t))
  (assert (step-all! ledger-2) '(3 #t))
  (assert (step-all! ledger-3) '(3 #t #t))
  (assert (step-all! ledger-4) '(1))
  (assert (step-all! ledger-5) '(1))

  (assert (step-all! ledger-1) '(5 #t))
  (assert (step-all! ledger-2) '(4 #t))
  (assert (step-all! ledger-3) '(3 #t #t))
  (assert (step-all! ledger-4) '(1))
  (assert (step-all! ledger-5) '(1))

  (assert (step-all! ledger-1) '(6 #t))
  (assert (step-all! ledger-2) '(4 #t))
  (assert (step-all! ledger-3) '(3 #t #t))
  (assert (step-all! ledger-4) '(1))
  (assert (step-all! ledger-5) '(1))

  (assert (step-all! ledger-1) '(7 #t))
  (assert (step-all! ledger-2) '(4 #t))
  (assert (step-all! ledger-3) '(3 #t #t))
  (assert (step-all! ledger-4) '(1))
  (assert (step-all! ledger-5) '(1))

  (assert (resolve ledger-1 '(-1 *bridge* ledger-2 -3
                                 *bridge* ledger-3 -1 *state* d e f) #f #f)
          64)

  (assert (resolve ledger-1 '(-1 *bridge* ledger-2 -1
                                 *bridge* ledger-3 -1
                                 *bridge* ledger-4 *state* g h i) #f #f)
          "hello")

  (assert (resolve ledger-1 '(-1 *bridge* ledger-2 -1
                                 *bridge* ledger-3 -1
                                 *bridge* ledger-5 *state* g h i) #t #f)
          (lambda (x) (equal? (cadr (assoc 'content x)) "world")))

  (assert (set-expr! ledger-1 '(*state* tick) 0) #t)
  (assert (step-all! ledger-1) '(8 #t))

  (assert (resolve ledger-1 '(1 *state* do pin) #f #f)
          '(directory ((this value) (that value)) #t))
  (assert (resolve ledger-1 '(1 *state* do pin this) #f #f) "yes")
  (assert (resolve ledger-1 '(1 *state* do pin that) #f #f) "yes")
  (assert (resolve ledger-1 '(1 *state* do not pin) #f #f) '(unknown))

  (assert ((ledger-1 'unpin!) '(1 *state* do pin that)) #t)
  (assert (resolve ledger-1 '(1 *state* do pin this) #f #f) "yes")
  (assert (resolve ledger-1 '(1 *state* do pin that) #f #f) '(unknown))

  (assert ((ledger-1 'pin!) '(-1 *state* do pin this)) #t)
  (assert ((ledger-1 'pin!) '(-2 *state* do pin this)) #t)
  (assert ((ledger-1 'pin!) '(-3 *state* do pin this)) #t)
  (assert ((ledger-1 'pin!) '(-4 *state* do pin this)) #t)
  (assert ((ledger-1 'pin!) '(-5 *state* do pin this)) #f)

  (assert (pin! ledger-1 '(-1 *bridge* ledger-2 *state* a b c)) #t)
  (assert (pin! ledger-1 '(-2 *bridge* ledger-2 -2 *state* a b c)) #t)
  (assert (resolve ledger-1 '(-1 *bridge* ledger-2 *state* a b c) #t #f)
          (lambda (res) (cadr (assoc 'pinned? res))))
  (assert (resolve ledger-1 '(-2 *bridge* ledger-2 -2 *state* a b c) #t #f)
          (lambda (res) (cadr (assoc 'pinned? res))))

  (assert ((ledger-1 'update-config!) '(public public-key) #u(0)) #t)
  (assert ((ledger-1 'update-config!) '(private secret-key) #u(1)) #t)
  (assert ((ledger-1 'update-config!) '(public window) 2) #t)
  (assert ((ledger-1 'update-code!) 'tree '(lambda (obj) obj)) #t)
  (assert ((ledger-1 'update-code!) 'chain '(lambda (obj) obj)) #t)

  (append "Success (" (object->string asserted) " checks)"))
