(macro (config standard-module chain tree ledger federation authorization . classes)
  (if (not (equal? (sync-digest *sync-state*)
                   #u(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
                      0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0)))
      (error 'upgrade-error "This Interface supports fresh installation only"))
  (set! chain (eval chain))
  (set! tree (eval tree))
  (set! ledger (eval ledger))
  (set! federation (eval federation))
  (set! authorization (eval authorization))
  (define (cfg key) (cadr (assoc key config)))
  (for-each (lambda (key)
              (if (not (assoc key config)) (error 'argument-error "Missing config")))
            '(root-secret interface-secret root))
  (set! config (append config `((clear? #t) (admins ()) (window #f)
				(interface ,(cfg 'interface-secret))
				(name ,(cfg 'interface-secret)) (bridge-accept auto))))
  (if (not (cfg 'clear?))
      (error 'upgrade-error "This Interface supports fresh installation only"))

  (define standard-source (eval standard-module))
  (define standard-module* (eval standard-source))
  (define standard-class (standard-module* 'class))
  (define (call body) (let ((result (sync-call `(*call* ,(cfg 'root-secret) ,body) #t)))
			(if (and (pair? result) (eq? (car result) 'error)) (apply error (cdr result)) result)))
  (define (set-query body) (sync-call `(*set-query* ,(cfg 'root-secret) ,body) #t))
  (define (set-step body) (sync-call `(*set-step* ,(cfg 'root-secret) ,body) #t))

  (let ((result (sync-call `(,(cfg 'root) ,(cfg 'root-secret) fresh) #t)))
    (if (and (pair? result) (eq? (car result) 'error))
        (apply error (cdr result))))
  (call `(lambda (root) (let* ((standard-module (eval ',standard-source))
			       (standard-node (standard-module 'make))
			       (standard-class (standard-module 'class))
			       (identity-nonce ,(random-byte-vector 32))
			       (identity-id (sync-hash (expression->byte-vector
							(list 'sync-web/journal-id/v1 identity-nonce))))
			       (identity `((id ,identity-id) (nonce ,identity-nonce)))
			       (journal-keys (crypto-generate (expression->byte-vector
							       (list 'sync-web/journal-signing-key/v1 identity-id
								     (sync-hash (expression->byte-vector ,(cfg 'root-secret)))))))
			       (federation-node
                                (standard-module 'init ',federation
                                 (list standard-node
                                       `((endpoint ,,(cfg 'interface))
                                         (bridge-accept ,',(cfg 'bridge-accept))
                                         (secret ,,(cfg 'interface-secret))
                                         (peers ()) (retired ())))))
                               (federation-live
                                (standard-module 'local ',federation federation-node))
                               (interface-public-key
                                ((federation-live 'config) '(interface-public-key)))
                               (ledger-config
                                `((public
                                   ((window ,,(cfg 'window)) (identity ,identity)
                                    (public-key ,(car journal-keys))
                                    (journal ((public-key ,(car journal-keys))
                                              (latest-rotation-index -1)))
                                    (interface ((public-key ,interface-public-key)
                                                (endpoint ,,(cfg 'interface))))
                                    (bridge-accept ,',(cfg 'bridge-accept))
                                    (name ,',(cfg 'name))))
                                  (private
                                   ((bridge-preapproval ())
                                    (journal ((rotation-indexes ())
                                              (pending-rotation ())))))))
                               (ledger-node
                                (standard-module 'init ',ledger
                                 (list standard-node ledger-config ',tree ',chain)))
                               (authorization-node
                                (standard-module 'init ',authorization '())))
			  ((root 'set!) '(root class standard-module) ',standard-source)
			((root 'set!) '(root class standard) standard-class)
			  ((root 'set!) '(root class chain) ',chain)
			  ((root 'set!) '(root class tree) ',tree)
			  ((root 'set!) '(root class ledger) ',ledger)
			  ((root 'set!) '(root class federation) ',federation)
			  ((root 'set!) '(root class authorization) ',authorization)
			  ((root 'set!) '(root object standard) standard-node)
			  ((root 'set!) '(root object ledger) ledger-node)
			  ((root 'set!) '(root object federation) (federation-live))
			  ((root 'set!) '(root object authorization) authorization-node)
			  ((root 'set!) '(interface secret)
			   (sync-hash (expression->byte-vector ,(cfg 'interface-secret))))
			  ((root 'set!) '(interface admins) ',(cfg 'admins))
			  ((root 'set!) '(interface endpoint) ,(cfg 'interface))
			  ((root 'set!) '(interface name) ',(cfg 'name))
			  ((root 'set!) '(interface private-key) '(nothing))
			  ((root 'set!) '(interface keys) '(nothing))
			  #t)))

  (let loop ((rest classes)) (if (pair? rest) (begin (call `(lambda (root)
							      ((root 'set!) '(root object ,(caar rest)) ,(cadar rest))))
						     (loop (cdr rest)))))

  (call `(lambda (root) ((root 'set!) '(root handler secret) (expression->byte-vector
							      '(lambda (root old-secret new-secret)
								 (let* ((module (eval ((root 'get) '(root class standard-module))))
									(std-node ((root 'get) '(root object standard)))
									(standard (module 'local ((root 'get) '(root class standard)) std-node))
									(ledger (module 'local ((root 'get) '(root class ledger))
										((root 'get) '(root object ledger))))
									(identity ((ledger 'config) '(public identity)))
									(id (cadr (assoc 'id identity)))
									(old (crypto-generate (expression->byte-vector
											       (list 'sync-web/journal-signing-key/v1 id (sync-hash
																	  (expression->byte-vector old-secret))))))
									(new (crypto-generate (expression->byte-vector
											       (list 'sync-web/journal-signing-key/v1 id (sync-hash
																	  (expression->byte-vector new-secret))))))
									(indexes ((ledger 'config) '(journal-rotation-indexes)))
									(previous (if (null? indexes) -1 (car (reverse indexes))))
									(index ((ledger 'size))))
								   (if (not (equal? (car old) (car new))) (begin ((ledger 'step!)
														  `((unix-time ,(system-time-unix))
														    (public-key ,(car new)) (secret-key ,(cdr new))
														    (rotation ((previous-key ,(car old)) (public-key ,(car new)) (signature
																						  ,(crypto-sign (cdr old) (expression->byte-vector
																									   (list 'sync-web/journal-key-rotation/v1 id index
																										 previous (car old) (car new)))))))))
														 ((root 'set!) '(root object ledger) (ledger))))
								   #t))))))

  (define query-once '(lambda (query) (let* ((function (cadr (assoc 'function query)))
					     (arguments (if (assoc 'arguments query) (cadr (assoc 'arguments query)) '()))
					     (authentication (and (assoc 'authentication query)
								  (cadr (assoc 'authentication query))))
					     (invocation (and (assoc 'invocation query) (cadr (assoc 'invocation query))))
					     (prepared (and (assoc 'prepared query) (cadr (assoc 'prepared query))))
					     (module (eval ((root 'get) '(root class standard-module))))
                                             (std-node ((root 'get) '(root object standard)))
                                             (standard (module 'local ((root 'get) '(root class standard)) std-node))
                                             (ledger (module 'local ((root 'get) '(root class ledger))
                                                             ((root 'get) '(root object ledger))))
                                             (federation (module 'local ((root 'get) '(root class federation))
                                                                 ((root 'get) '(root object federation))))
                                             (authorization (module 'local ((root 'get) '(root class authorization))
                                                                    ((root 'get) '(root object authorization))))
                                             (context '()) (auth-head #f) (ancestor? #f)
					     (delegated? #f))

					(define (arg name) (let ((entry (assoc name arguments))) (and entry (cadr entry))))
					(define (set-alist values key value) (let loop ((in values) (out '()))
									       (cond ((null? in) (reverse (cons (list key value) out))) ((eq? (caar in) key)
																	 (append (reverse out) (cons (list key value) (cdr in))))
										     (else (loop (cdr in) (cons (car in) out))))))
					(if (or (assoc 'meta arguments) (assoc 'metas arguments) (assoc 'meta? arguments))
					    (error 'argument-error "Metadata is not supported"))
					(define (with-auth request) (cond (authentication
									   (append request `((authentication ,authentication))))
									  (invocation (append request `((invocation ,invocation))))
									  (else request)))
					(define (self-call data)
					  (set! delegated? #t)
					  (sync-call (with-auth
					              `((function ,function) (arguments ,arguments)
					                ,@(if data `((prepared ,data)) '()))) #t))
					(define (failure result) (let ((entry (and (pair? result) (pair? (car result))
										   (assoc 'failure result))))
								   (if entry (let ((value (cadr entry))) (error (cadr (assoc 'tag value))
														(cadr (assoc 'message value))))
								       result)))
					(define (federation-call method operands) (let* ((input (if (not prepared) operands
												    (append (reverse (cdr (reverse operands)))
													    (list `((value ,(car (reverse operands)))
														    (continuation ,prepared))))))
											 (result (apply (federation method) (cons ledger input)))
											 (next (and (pair? result) (pair? (car result)) (assoc 'continuation result))))
										    (cond (next (failure (self-call (cadr next)))) (prepared result)
											  (else (failure result)))))
					(define (authenticate) (if invocation
								   (let ((source (arg-from invocation 'route-source))
									 (target (arg-from invocation 'route-target)))
								     (if (and (null? source) (null? target))
									 (let ((identity (arg-from invocation 'identity))) (if (not (equal?
																     (sync-hash (expression->byte-vector
																		 (arg-from invocation 'credentials)))
																     ((root 'get) '(interface secret))))
															       (error 'authentication-error "Authentication failed"))
									      (if (eq? identity '*journal*) '()
										  (if (eq? identity '*public*) '(*public*) `(*state* ,identity))))
									 (let* ((result ((federation 'authenticate) ledger
											 `((function ,function) (arguments ,arguments)
											   (invocation ,invocation)))))
									   (set! context (cadr (assoc 'context result)))
									   (set! auth-head (and (assoc 'data-head result)
												(cadr (assoc 'data-head result))))
									   (cadr (assoc 'principal result)))))
								   (if (not authentication) '(*public*)
								       (let ((principal (or (arg-from authentication 'identity) '())))
									 (if (not (equal? (sync-hash (expression->byte-vector
												      (arg-from authentication 'credentials)))
											  ((root 'get) '(interface secret))))
									     (error 'authentication-error "Authentication failed"))
									 principal))))
					(define (arg-from values key) (let ((entry (and (list? values) (assoc key values))))
									(and entry (cadr entry))))
					(define (authorize) (let* ((principal (authenticate)) (path (let ((path (arg 'path)))
												      (if (and (eq? function 'trace) (arg 'index) (or (null? path)
																		      (not (integer? (car path)))))
													  (cons (arg 'index) path) path)))
								   (admins ((root 'get) '(interface admins)))
								   (remote (assoc 'authentication-index context))
								   (ctx `((latest-index ,(- ((ledger 'size)) 1))
									  ,@(if remote `((authentication-index ,(cadr remote))) '())))
								   (owner (arg 'user))
								   (direct? (or (and (not remote)
										     (or (null? principal) (member principal admins)))
										(and (memq function '(authorizations authorize! deauthorize!))
										     owner (equal? owner principal))))
								   (decision (if direct? 'direct (if (eq? function 'set-batch!)
												     (let loop ((paths (arg 'paths))) (if (null? paths) 'direct
																	  (and (eq? ((authorization 'authorized?)
																		     principal ctx (car paths) 'set!)
																		    'direct)
																	       (loop (cdr paths)))))
												     (and path ((authorization 'authorized?)
														principal ctx path function))))))
							      (if (not decision) (error 'authorization-error "Not authorized"))
							      (set! ancestor? (eq? decision 'ancestor))
							      principal))
					(define (encode value expression?) (cond ((equal? value '(nothing)) value)
										 (expression? (expression->byte-vector value))
										 ((byte-vector? value) value)
										 (else (error 'value-error "Expected byte-vector"))))
					(define (decode value expression?) (cond ((not expression?) value)
										 ((byte-vector? value) (byte-vector->expression value))
										 ((and (pair? value) (pair? (car value)) (assoc 'content value))
										  (set-alist value 'content (decode (cadr (assoc 'content value)) #t)))
										 (else value)))
					(define (stage-directory value) (if (not ancestor?) value
									    (let ((entries (and (pair? value) (eq? (car value) 'directory) (cadr value))))
									      (if (not entries) (error 'authorization-error "Not a directory"))
									      `(directory ,(let loop ((in entries) (out '())) (if (null? in) (reverse out)
																  (let* ((name (caar in)) (text (symbol->string name))) (loop (cdr in)
																							      (if (and (> (length text) 1) (char=? (text 0) #\*)
																								       (char=? (text (- (length text) 1)) #\*))
																								  out (cons (car in) out)))))) #f))))
					(define* (hydrate path (index -1))
					  ((federation 'route) ledger
					   `((operation hydrate) (path ,path) (index ,index))))
					(define (federate) (if (not (memq function '(get set! resolve)))
							       (error 'api-error "Not federated"))
					  (if (not (equal? (sync-hash
							    (expression->byte-vector (arg-from invocation 'credentials)))
							   ((root 'get) '(interface secret))))
					      (error 'authentication-error "Authentication failed"))
					  ((federation 'invoke) ledger function arguments (arg-from invocation 'route-target)
					   (arg-from invocation 'history-indexes)
					   (arg-from invocation 'identity)))
					(define (config-view path)
  (if (not (and (pair? path) (eq? (car path) 'private)))
      ((ledger 'config) path)
      (case (and (pair? (cdr path)) (cadr path))
        ((bridge bridge-retired)
         ((federation 'config)
          (cons (if (eq? (cadr path) 'bridge) 'peers 'retired)
                (cddr path))))
        ((bridge-identity)
         (let* ((alias (and (pair? (cddr path)) (caddr path)))
                (active ((federation 'config) `(peers ,alias identity-id))))
           (if (null? active)
               ((federation 'config) `(retired ,alias identity-id)) active)))
        ((bridge-preapproval)
         ((ledger 'config) (cons 'peer-preapproval (cddr path))))
        (else '()))))

					(if (and invocation (pair? (arg-from invocation 'route-target))) (federate)
					    (let ((result (case function ((route) ((federation 'route) ledger
										   `((route-source ,(or (arg 'route-source) '()))
										     (route-target ,(arg 'route-target))
										     (index ,(or (arg 'index) -1))
										     ,@(if (assoc 'history-indexes arguments)
											   `((history-indexes ,(arg 'history-indexes))) '())
										     ,@(if (assoc 'history-head-index arguments) `((history-head-index
																    ,(arg 'history-head-index))) '())
										     (roots ,(or (arg 'roots) '())))))
								((size) ((ledger 'size)))
								((info) ((ledger 'descriptor) -1))
								((synchronize!) ((federation 'synchronize!) ledger arguments))
								(else (authorize) (case function ((get) (stage-directory
													 (decode ((ledger 'get) (arg 'path)) (arg 'expression?))))
											((set!) ((ledger 'set!) (arg 'path)
												 (encode (arg 'value) (arg 'expression?))))
											((set-batch!) ((ledger 'set-batch!) (map (lambda (path value)
																   (list path (encode value (arg 'expression?))))
																 (arg 'paths) (arg 'values))))
											((resolve) (let* ((path (arg 'path)) (head (or (arg 'head) auth-head))
													  (attempt ((ledger 'resolve) path #f #f head ancestor?))
													  (head (if (and (not head) (equal? attempt '(unknown))
															 (pair? path)
															 (let ((segment (if (integer? (car path))
																	    (cadr path) (car path))))
															   (or (eq? segment '*bridge*)
															       (and (symbol? segment) (not (memq segment
																				 '(*state* *transition* *crypto*)))))))
														    (hydrate path) head)))
												     (decode ((ledger 'resolve) path (arg 'pinned?) (arg 'proof?)
													      head ancestor?)
													     (arg 'expression?))))
											((trace) (let* ((path (arg 'path)) (index (or (arg 'index) -1))
													(trace-path (cons index path))
													(head (arg 'head)))
												   (if head ((ledger 'trace) path head)
												       (let* ((resolve-path (if (and (pair? path) (integer? (car path)))
													 path (cons index path)))
											  (attempt ((ledger 'resolve) resolve-path)))
													 (if (equal? attempt '(unknown)) ((ledger 'trace) path
																	  (hydrate path index))
													     ((ledger 'trace) trace-path))))))
											((pin!) (if (arg 'response)
                                                      ((ledger 'pin!) (arg 'path) (arg 'response))
                                                      (let* ((path (arg 'path))
                                                             (attempt ((ledger 'resolve) path)))
                                                        (if (not (equal? attempt '(unknown)))
                                                            ((ledger 'pin!) path #f)
                                                            (sync-call
                                                             (with-auth
                                                              `((function pin!)
                                                                (arguments
                                                                 ,(set-alist
                                                                   arguments 'response
                                                                   ((ledger 'trace) path
                                                                    (hydrate path)))))) #t)))))
                                          ((unpin!) ((ledger 'unpin!) (arg 'path)))
											((bridge!) (federation-call 'bridge! (list (arg 'name)
																   `((interface ,(arg 'interface))
																     (remote-name ,(arg 'remote-name))))))
											((delete-bridge!) ((authorization 'deauthorize!)
													   `((principal-prefix (,(arg 'name)))))
											 ((federation 'delete-bridge!) ledger (arg 'name)))
											((authorizations) ((authorization 'authorizations) (arg 'user)))
											((authorize!) ((authorization 'authorize!)
												       `((user ,(arg 'user)) (rule ,(arg 'rule))
													 (latest-index ,(- ((ledger 'size)) 1)))))
											((deauthorize!) ((authorization 'deauthorize!)
													 `((user ,(arg 'user)) (rule ,(arg 'rule)))))
											((config) (config-view (or (arg 'path) '())))
											((update-config!) ((ledger 'update-config!)
													   `((path ,(arg 'path)) (value ,(arg 'value))))
											 (if (equal? (arg 'path) '(public bridge-accept))
											     ((federation 'update-config!) `((path (bridge-accept))
															     (value ,(arg 'value))))) #t)
											((*secret*)
                         (let* ((secret (arg 'secret))
                                (committed
                                 ((ledger 'resolve)
                                  '(-1 *crypto* interface public-key)))
                                (public-key
                                 ((federation 'update-config!)
                                  `((path (rotate-key))
                                    (value ((secret ,secret)
                                            (committed-public-key ,committed)))))))
                           ((root 'set!) '(interface secret)
                            (sync-hash (expression->byte-vector secret)))
                           ((ledger 'update-config!)
                            `((path (public interface public-key))
                              (value ,public-key)))))
                                          ((*admins-get*) ((root 'get) '(interface admins)))
											((*admins-set*) (if (not (let loop ((in (arg 'admins))) (or (null? in)
																		    (and (pair? (car in)) (eq? (caar in) '*state*)
																			 (pair? (cdar in))
																			 (symbol? (cadar in))
																			 (null? (cddar in))
																			 (loop (cdr in))))))
													    (error 'argument-error "Admins must be local"))
											 ((root 'set!) '(interface admins) (arg 'admins)))
											((*window-set*) ((ledger 'update-config!)
													 `((path (public window)) (value ,(arg 'value)))))
											(else (error 'api-error "Unknown Interface function")))))))
					      (if (not delegated?)
					          (begin
					            ((root 'set!) '(root object ledger) (ledger))
					            ((root 'set!) '(root object federation) (federation))
					            ((root 'set!) '(root object authorization) (authorization))))
					      result)))))

  (set-query `(lambda (root query) (define (arg-from values key)
				     (let ((entry (and (list? values) (assoc key values)))) (and entry (cadr entry))))
		      (let ((once ,query-once)) (if (not (eq? (cadr (assoc 'function query)) 'batch!))
						    (once query)
						    (let ((auth (assoc 'authentication query))) (map (lambda (item)
												       (once (if auth (append item (list auth)) item)))
												     (arg-from (cadr (assoc 'arguments query)) 'queries)))))))

  (define step-once '(lambda (root secret query)
		       (let* ((module (eval ((root 'get) '(root class standard-module))))
                              (std-node ((root 'get) '(root object standard)))
                              (standard (module 'local ((root 'get) '(root class standard)) std-node))
                              (ledger (module 'local ((root 'get) '(root class ledger))
                                              ((root 'get) '(root object ledger))))
                              (federation (module 'local ((root 'get) '(root class federation))
                                                  ((root 'get) '(root object federation)))))
                         (define (self query blocking?) (sync-call `(*step* ,secret ,query) blocking?))
			 (define (run method operands data query) (let* ((input (if data
										    (append (reverse (cdr (reverse operands)))
											    (list `((value ,(car (reverse operands))) (continuation ,data))))
										    operands))
									 (result (apply (federation method) (cons ledger input)))
									 (next (and (pair? result) (pair? (car result)) (assoc 'continuation result))))
								    (if next (self (append query (list (cadr next))) #t) result)))
			 (define (commit) (let* ((identity ((ledger 'config) '(public identity)))
						 (id (cadr (assoc 'id identity)))
						 (keys (crypto-generate (expression->byte-vector
									 (list 'sync-web/journal-signing-key/v1 id
									       (sync-hash (expression->byte-vector secret))))))
						 (size ((ledger 'step!) `((unix-time ,(system-time-unix))
									  (public-key ,(car keys))
									  (secret-key ,(cdr keys)))))
						 (configured ((ledger 'config) '(public interface public-key)))
						 (committed (if (= size 0) '() ((ledger 'resolve)
										'(-1 *crypto* interface public-key))))
						 )
					    ((federation 'update-config!)
					     `((path (commit-key))
					       (value ((configured ,configured) (committed ,committed)))))
					    size))
			 (let* ((query (if (null? query) '(ledger-step) query)) (result (case (car query)
											  ((ledger-step) (if (and (pair? (cdr query)) (cadr query)) (commit)
													     (let ((ops (cadr (assoc 'operations ((federation 'step!) ledger)))))
													       (for-each (lambda (op) (self op #f)) ops)
													       (self '(ledger-step #t) #t))))
											  ((bridge-synchronize!) (run 'bridge-synchronize! (list (cadr query))
														      (and (pair? (cddr query)) (caddr query))
														      `(bridge-synchronize! ,(cadr query))))
											  (else (error 'api-error "Unknown step operation")))))
			   ((root 'set!) '(root object ledger) (ledger))
			   ((root 'set!) '(root object federation) (federation))
			   result))))
  (set-step step-once)
  "Installed interface")
