use super::*;

pub(crate) fn normalize_rat(n:i64,d:i64)->Value{
    if d==0 { return Value::Float(f64::NAN); }
    let mut n=n; let mut d=d;
    if d<0 { n=-n; d=-d; }
    let g=gcd_i(n,d).max(1);
    let n=n/g; let d=d/g;
    if d==1 { Value::Int(n) } else { Value::Rational(n,d) }
}
pub(crate) fn rat_parts(v:&Value)->Option<(i64,i64)>{match v{Value::Int(n)=>Some((*n,1)),Value::Rational(n,d)=>Some((*n,*d)),_=>None}}
pub(crate) fn to_f64(v:&Value)->Result<f64>{match v{Value::Int(n)=>Ok(*n as f64),Value::Rational(n,d)=>Ok(*n as f64 / *d as f64),Value::Float(x)=>Ok(*x),Value::NumberLiteral(_,f)=>Ok(*f),_=>Err(SchemeError::new("wrong-type-arg",vec![v.clone()]))}}
pub(crate) fn to_complex(v:&Value)->Result<(f64,f64)>{match v{Value::Complex(r,i)=>Ok((*r,*i)),_=>Ok((to_f64(v)?,0.0))}}
pub(crate) fn add2(a:Value,b:Value)->Result<Value>{match (a,b){(Value::Complex(ar,ai),b)=>{let (br,bi)=to_complex(&b)?;Ok(Value::Complex(ar+br,ai+bi))},(a,Value::Complex(br,bi))=>{let (ar,ai)=to_complex(&a)?;Ok(Value::Complex(ar+br,ai+bi))},(Value::Float(x),b)=>Ok(Value::Float(x+to_f64(&b)?)),(a,Value::Float(y))=>Ok(Value::Float(to_f64(&a)?+y)),(a,b)=>{let (an,ad)=rat_parts(&a).ok_or_else(||SchemeError::new("wrong-type-arg",vec![Value::string("~A ~:D argument, ~S, is ~A but should be ~A"), Value::symbol("+"), Value::Int(if matches!(a,Value::Undefined){1}else{2}), a.clone(), Value::string(if matches!(a,Value::Undefined){"an undefined object"}else{"a symbol"}), Value::string("a number")]))?; let (bn,bd)=rat_parts(&b).ok_or_else(||SchemeError::new("wrong-type-arg",vec![Value::string("~A ~:D argument, ~S, is ~A but should be ~A"), Value::symbol("+"), Value::Int(if matches!(b,Value::Undefined){1}else{2}), b.clone(), Value::string(if matches!(b,Value::Undefined){"an undefined object"}else{"a symbol"}), Value::string("a number")]))?; Ok(normalize_rat(an*bd+bn*ad,ad*bd))}}}
pub(crate) fn sub2(a:Value,b:Value)->Result<Value>{match (a,b){(Value::Complex(ar,ai),b)=>{let (br,bi)=to_complex(&b)?;Ok(Value::Complex(ar-br,ai-bi))},(a,Value::Complex(br,bi))=>{let (ar,ai)=to_complex(&a)?;Ok(Value::Complex(ar-br,ai-bi))},(Value::Float(x),b)=>Ok(Value::Float(x-to_f64(&b)?)),(a,Value::Float(y))=>Ok(Value::Float(to_f64(&a)?-y)),(a,b)=>{let (an,ad)=rat_parts(&a).ok_or_else(||SchemeError::new("wrong-type-arg",vec![a.clone()]))?; let (bn,bd)=rat_parts(&b).ok_or_else(||SchemeError::new("wrong-type-arg",vec![b.clone()]))?; Ok(normalize_rat(an*bd-bn*ad,ad*bd))}}}
pub(crate) fn mul2(a:Value,b:Value)->Result<Value>{match (a,b){(Value::Complex(ar,ai),b)=>{let (br,bi)=to_complex(&b)?;Ok(Value::Complex(ar*br-ai*bi,ar*bi+ai*br))},(a,Value::Complex(br,bi))=>{let (ar,ai)=to_complex(&a)?;Ok(Value::Complex(ar*br-ai*bi,ar*bi+ai*br))},(Value::Float(x),b)=>Ok(Value::Float(x*to_f64(&b)?)),(a,Value::Float(y))=>Ok(Value::Float(to_f64(&a)?*y)),(a,b)=>{let (an,ad)=rat_parts(&a).ok_or_else(||SchemeError::new("wrong-type-arg",vec![a.clone()]))?; let (bn,bd)=rat_parts(&b).ok_or_else(||SchemeError::new("wrong-type-arg",vec![b.clone()]))?; Ok(normalize_rat(an*bn,ad*bd))}}}
pub(crate) fn div2(a:Value,b:Value)->Result<Value>{match (a,b){(a,Value::Complex(br,bi))=>{let (ar,ai)=to_complex(&a)?; let den=br*br+bi*bi; if den==0.0{return Err(SchemeError::new("division-by-zero",vec![]));} Ok(Value::Complex((ar*br+ai*bi)/den,(ai*br-ar*bi)/den))},(Value::Complex(ar,ai),b)=>{let (br,bi)=to_complex(&b)?; let den=br*br+bi*bi; if den==0.0{return Err(SchemeError::new("division-by-zero",vec![]));} Ok(Value::Complex((ar*br+ai*bi)/den,(ai*br-ar*bi)/den))},(Value::Float(x),b)=>{let y=to_f64(&b)?; if y==0.0{return Err(SchemeError::new("division-by-zero",vec![]));} Ok(Value::Float(x/y))},(a,Value::Float(y))=>{if y==0.0{return Err(SchemeError::new("division-by-zero",vec![]));} Ok(Value::Float(to_f64(&a)?/y))},(a,b)=>{let (an,ad)=rat_parts(&a).ok_or_else(||SchemeError::new("wrong-type-arg",vec![a.clone()]))?; let (bn,bd)=rat_parts(&b).ok_or_else(||SchemeError::new("wrong-type-arg",vec![b.clone()]))?; if bn==0{return Err(SchemeError::new("division-by-zero",vec![]));} Ok(normalize_rat(an*bd,ad*bn))}}}
pub(crate) fn fold_num(args:&[Value], init:Value, op:fn(Value,Value)->Result<Value>)->Result<Value>{let mut acc=init; for a in args{acc=op(acc,a.clone())?;} Ok(acc)}
pub(crate) fn as_i64(v:&Value)->Result<i64>{ match v { Value::Int(n)=>Ok(*n), Value::Rational(n,d) if n%d==0=>Ok(n/d), Value::Float(f)=>Ok(*f as i64), Value::NumberLiteral(_,f)=>Ok(*f as i64), _=>Err(SchemeError::new("wrong-type-arg",vec![v.clone()])) } }
pub(crate) fn as_f64(v:&Value)->Result<f64>{ to_f64(v) }
pub(crate) fn as_usize(v:Option<&Value>)->Result<usize>{ Ok(as_i64(v.ok_or_else(||SchemeError::new("wrong-number-of-args",vec![]))?)? as usize) }
pub(crate) fn cmp(args:&[Value], f:fn(f64,f64)->bool)->Result<Value>{ for w in args.windows(2){ if !f(as_f64(&w[0])?,as_f64(&w[1])?){return Ok(Value::Bool(false));}} Ok(Value::Bool(true)) }