(lambda (make-interface-harness)
  (with-let (make-interface-harness :journals 2 :tick 1)
    (define (bridge-from-renamed)
      (raw journal-1
        '((function bridge!)
          (arguments ((name journal-2)
                      (interface "http://journal-2.test/interface")
                      (remote-name renamed)))
          (authentication ((credentials "http://journal-1.test/interface"))))))
    (test-submit ((*journal* journal-1 'step!)) :expect integer?)
    (test-submit ((*journal* journal-2 'step!)) :expect integer?)
    (test-report)
    (test-submit ((*journal* journal-1 'update-config!)
                  '((path (public name)) (value "renamed"))) :expect #t)
    (test-submit ((*journal* journal-1 'step!)) :expect integer?)
    (test-report)
    (test-submit (bridge-from-renamed) :expect #t)
    (test-report)
    (test-submit ((*journal* journal-2 'config) '((path (private bridge renamed)))) :expect pair?)
    (test-report)
    (test-submit ((*journal* journal-1 'update-config!)
                  '((path (public interface endpoint))
                    (value "http://journal-1-renamed.test/interface"))) :expect #t)
    (test-submit ((*journal* journal-1 'step!)) :expect integer?)
    (test-report)
    (test-submit ((*anonymous* journal-1 'info))
      :expect (lambda (info)
                (equal? (cadr (assoc 'endpoint (cadr (assoc 'interface info))))
                        "http://journal-1-renamed.test/interface")))
    (test-report)

    ;; Galactica deletes its reciprocal, Ender keeps its matching local edge.
    (test-submit ((*journal* journal-2 'delete-bridge!) 'renamed) :expect #t)
    (test-report)
    (test-submit (bridge-from-renamed) :expect #t)
    (test-report)

    ;; Two-sided teardown, keeping the released retired records on both sides.
    (test-submit ((*journal* journal-2 'delete-bridge!) 'renamed) :expect #t)
    (test-submit ((*journal* journal-1 'delete-bridge!) 'journal-2) :expect #t)
    (test-report)
    (test-submit (bridge-from-renamed) :expect #t)
    (test-report)))
