(lambda (make-interface-harness)
  (with-let (make-interface-harness :journals 1 :tick 1)
    (define url "http://journal-1-renamed.test/interface")
    (define (error-result? result)
      (and (pair? result) (eq? (car result) 'error)))
    (define (endpoints)
      (raw journal-1
        '(*call* "pass-1"
          (lambda (root)
            (let ((ledger (sync-eval ((root 'get) '(root object ledger))))
                  (federation (sync-eval ((root 'get) '(root object federation)))))
              (list ((ledger 'config) '(public interface endpoint))
                    ((federation 'config) '(endpoint))))))))
    (test-submit ((alice journal-1 'update-config!)
                  `((path (public interface endpoint)) (value ,url)))
      :expect error-result?)
    (test-submit (endpoints)
      :expect '("http://journal-1.test/interface" "http://journal-1.test/interface"))
    (test-submit ((*journal* journal-1 'update-config!)
                  `((path (public interface endpoint)) (value ,url))) :expect #t)
    (test-submit (endpoints) :expect (list url url))
    (test-submit ((*journal* journal-1 'update-config!)
                  '((path (public name)) (value "renamed"))) :expect #t)
    (test-submit (endpoints) :expect (list url url))
    (test-report)
    ;; Simulate already-diverged persisted Federation configuration in this test DB.
    (test-submit
      (raw journal-1
        '(*call* "pass-1"
          (lambda (root)
            (let ((federation (sync-eval ((root 'get) '(root object federation)))))
              ((federation 'update-config!)
                '((path (endpoint)) (value "http://journal-1.test/interface")))
              ((root 'set!) '(root object federation) (federation))
              #t)))) :expect #t)
    (test-submit (endpoints) :expect (list url "http://journal-1.test/interface"))
    (test-submit ((*journal* journal-1 'update-config!)
                  `((path (public interface endpoint)) (value ,url))) :expect #t)
    (test-submit (endpoints) :expect (list url url))
    (test-report)))
