(lambda (make-interface-harness)
  (with-let (make-interface-harness :journals 3 :users '(alice bob) :legacy? #t)

    (define (error-result? result)
      (and (pair? result) (eq? (car result) 'error)))

    (define (collect action)
      (test-report)
      (test-submit action)
      (test-await))

    (define (state-digest-action journal)
      (raw journal
           `(*call* ,(journal 'root-secret)
             (lambda (root) (sync-digest *sync-state*)))))

    (define (snapshot journal)
      (collect
       (raw journal
            `(*call* ,(journal 'root-secret)
              (lambda (root)
                (let* ((module (eval ((root 'get) '(root class standard-module))))
                       (ledger (module 'local ((root 'get) '(root class ledger))
                                       ((root 'get) '(root object ledger))))
                       (config ((ledger 'config)))
                       (public (cadr (assoc 'public config)))
                       (identity (and (assoc 'identity public)
                                      (cadr (assoc 'identity public))))
                       (salt (and (assoc 'key-derivation-salt public)
                                  (cadr (assoc 'key-derivation-salt public))))
                       (size ((ledger 'size)))
                       (last (- size 1)))
                  `((size ,size)
                    (identity ,identity)
                    (salt ,salt)
                    (public-key ,(cadr (assoc 'public-key public)))
                    (last-digest ,(and (>= last 0)
                                       ((ledger '~child)
                                        ((ledger '~field!) 'perm) 'digest last)))
                    (signed-head ,((ledger 'signed-head) -1)))))))))

    (test-submit ((*journal* journal-1 'set!) '(*state* alice value) "legacy")
                 :expect #t)
    (test-submit ((*journal* journal-2 'set!) '(*state* bob document) "peer")
                 :expect #t)
    (test-submit ((*journal* journal-3 'set!) '(*state* alice atomic) "unchanged")
                 :expect #t)
    (test-submit ((*journal* journal-1 'step!)) :expect 1)
    (test-submit ((*journal* journal-2 'step!)) :expect 1)
    (test-submit ((*journal* journal-3 'step!)) :expect 1)
    (test-report)
    ;; A malformed required migration value fails the Root call atomically.
    (test-submit
     ((*journal* journal-3 'update-config!)
      '((path (public identity id))
        (value #u(0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
                   0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0))))
     :expect #t)
    (let ((before-failure (collect (state-digest-action journal-3))))
      (test-submit (update-interface journal-3 '() 4 #f) :expect error-result?)
      (test-report)
      (test-submit (state-digest-action journal-3) :expect before-failure))
    (test-report)
    (test-submit ((*journal* journal-1 'bridge!) journal-2) :expect #t)
    (test-report)
    (test-submit ((*journal* journal-2 'step!)) :expect integer?)
    (test-submit ((*journal* journal-1 'bridge!) journal-2) :expect #t)
    (test-report)
    (test-submit ((*journal* journal-1 'step!)) :expect integer?)
    (test-report)
    (let* ((before (snapshot journal-1))
           (before-peer (snapshot journal-2))
           (identity (cadr (assoc 'identity before)))
           (identity-id (cadr (assoc 'id identity)))
           (before-key (cadr (assoc 'public-key before)))
           (before-size (cadr (assoc 'size before)))
           (before-digest (cadr (assoc 'last-digest before)))
           (old-head (cadr (assoc 'signed-head before)))
           (peer-identity (cadr (assoc 'identity before-peer)))
           (peer-identity-id (cadr (assoc 'id peer-identity)))
           (peer-key (cadr (assoc 'public-key before-peer)))
           (peer-size (cadr (assoc 'size before-peer)))
           (peer-digest (cadr (assoc 'last-digest before-peer))))
      (test-submit
       ((*journal* journal-1 'update-config!)
        `((path (private bridge-preapproval unused)) (value ,identity-id)))
       :expect #t)
      (test-submit (update-interface journal-1 '() 4 #f)
                   :expect "Installed interface")
      (test-submit (update-interface journal-2 '() 4 #f)
                   :expect "Installed interface")
      (test-submit
       ((*journal* journal-2 'authorize!)
        '((user (*state* bob))
          (rule ((principal (journal-1 *state* alice))
                 (key-index (-20 -1)) (path (document))
                 (put! #f) (use! ((read-only? #t))) (run! #f)
                 (retrieve #t)))))
       :expect #t)
      (test-report)
      ;; The one transition is forward-only; already migrated state cannot be
      ;; reclassified a second time.
      (test-submit (update-interface journal-1 '() 4 #f)
                   :expect error-result?)
      (test-report)

      (let ((after (snapshot journal-1))
            (after-peer (snapshot journal-2)))
        (test-submit
         (raw journal-1
              `(*call* "pass-1"
                (lambda (root)
                  (let* ((module (eval ((root 'get) '(root class standard-module))))
                         (standard (module 'local ((root 'get) '(root class standard))
                                           ((root 'get) '(root object standard))))
                         (ledger (module 'local ((root 'get) '(root class ledger))
                                         ((root 'get) '(root object ledger))))
                         (federation
                          (module 'local ((root 'get) '(root class federation))
                                  ((root 'get) '(root object federation))))
                         (head ((standard 'deserialize) ',old-head)))
                    (list
                     (= ((ledger 'size)) ,before-size)
                     (equal? ((ledger '~child) ((ledger '~field!) 'perm)
                              'digest ,(- before-size 1)) ',before-digest)
                     (equal? ((federation '~signature-verify)
                              head ',before-key -1) ',before-key))))))
         :expect '(#t #t #t))
        (test-submit
         ((*anonymous* journal-1 'info))
         :expect (lambda (result)
                   (and (not (assoc 'identity result))
                        (equal? (cadr (assoc 'key-derivation-salt result))
                                identity-id)
                        (equal? (cadr (assoc 'public-key result)) before-key))))
        (test-submit
         ((*journal* journal-1 'config)
          '((path (private bridge-preapproval unused))))
         :expect '())
        (test-submit
         ((*anonymous* journal-2 'info))
         :expect (lambda (result)
                   (and (not (assoc 'identity result))
                        (equal? (cadr (assoc 'key-derivation-salt result))
                                peer-identity-id)
                        (equal? (cadr (assoc 'public-key result)) peer-key)
                        (= (cadr (assoc 'size after-peer)) peer-size)
                        (equal? (cadr (assoc 'last-digest after-peer))
                                peer-digest))))
        (test-submit ((alice journal-1 'use!) '(*state* alice value))
                     :expect "legacy")
        (test-submit ((alice journal-1 journal-2 'use!) '(*state* bob document))
                     :expect "peer")
        (test-submit ((*journal* journal-1 'bridge!) journal-2) :expect #t)
        (test-submit
         ((*journal* journal-1 'put!) '(*state* alice successor) "v2")
         :expect #t)
        (test-submit ((*journal* journal-1 'step!)) :expect (+ before-size 1))
        (test-submit
         (raw journal-1
              '(*call* "pass-1"
                (lambda (root)
                  (let* ((module (eval ((root 'get) '(root class standard-module))))
                         (standard (module 'local ((root 'get) '(root class standard))
                                           ((root 'get) '(root object standard))))
                         (ledger (module 'local ((root 'get) '(root class ledger))
                                         ((root 'get) '(root object ledger))))
                         (head ((standard 'deserialize) ((ledger 'signed-head) -1))))
                    (list
                     ((standard 'deep-get) head '(-1 (*crypto* journal format-version)))
                     ((standard 'deep-get) head '(-1 (*crypto* journal key-derivation-salt)))
                     ((standard 'deep-get) head '(-1 (*crypto* journal identity id)))
                     ((standard 'deep-get) head '(-1 (*crypto* journal identity nonce)))))))))
         :expect (lambda (result)
                   (and (= (car result) 2)
                        (equal? (cadr result) identity-id)
                        (equal? (caddr result) '(nothing))
                        (equal? (cadddr result) '(nothing))))))

    (test-report)))
