#!/bin/sh
set -eu

real=/usr/lib/llvm21/bin/llvm-config
if test "$#" -eq 2 && test "$1" = --libs && test "$2" = --link-static; then
  "$real" "$@"
  "$real" --system-libs --link-static
  printf '%s\n' '-llzma -lpthread'
else
  exec "$real" "$@"
fi
