name: All

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: "all"
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run records test suite
        run: ./tests/test.sh "docker run --rm ghcr.io/sandialabs/sync-journal/journal-sdk"
