name: Docs

on:
  push:
    branches: ["**"]
    paths: ["docs/**"]
  pull_request:
    branches: ["main"]
    paths: ["docs/**"]

concurrency:
  group: "docs-${{ github.ref }}"
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install packages
        working-directory: docs/info
        run: npm install
      - name: Create documents
        working-directory: docs/info
        run: npm run build
      - name: Upload documents artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs/info/dist/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
