name: General Journal

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: "general"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Login to Github registry
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build versioned Docker image
        run: |
          version=$( cat ./compose/general/version.txt )
          docker build ./compose/general --tag ghcr.io/${{ github.repository }}/general:$version
      - name: Push versioned Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          version=$( cat ./compose/general/version.txt )
          docker push ghcr.io/${{ github.repository }}/general:$version
      - name: Retag and push latest Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          version=$( cat ./compose/general/version.txt )
          docker tag ghcr.io/${{ github.repository }}/general:$version \
                     ghcr.io/${{ github.repository }}/general:latest 
          docker push ghcr.io/${{ github.repository }}/general:latest
