name: Social Agent

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: "social-agent"
  cancel-in-progress: true

jobs:
  all:
    runs-on: ubuntu-latest
    permissions: write-all
    # if: github.ref == 'refs/heads/main'
    steps:
      - name: Login to Github registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build and push versioned Docker image
        run: |
          version=$( cat ./firewheel/model-components/social-agent/version.txt )
          docker build ./firewheel/model-components/social-agent/docker --tag ghcr.io/${{ github.repository }}/social-agent:$version
          docker push ghcr.io/${{ github.repository }}/social-agent:$version
      - name: Retag and push latest Docker image
        run: |
          version=$( cat ./firewheel/model-components/social-agent/version.txt )
          docker tag ghcr.io/${{ github.repository }}/social-agent:$version \
                     ghcr.io/${{ github.repository }}/social-agent:latest 
          docker push ghcr.io/${{ github.repository }}/social-agent:latest
