name: Social Agent

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: "social-agent"
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install social-agent test dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ./firewheel/model-components/social-agent/docker/requirements.txt
      - name: Run social-agent tests
        run: |
          python -m unittest discover -s ./firewheel/model-components/social-agent/docker/tests -p "test_*.py" -v

  publish:
    needs: test
    runs-on: ubuntu-latest
    permissions: write-all
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Login to Github registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build and push versioned Docker image
        run: |
          version=$( cat ./firewheel/model-components/social-agent/version.txt )
          docker build ./firewheel/model-components/social-agent/docker --tag ghcr.io/${{ github.repository }}/social-agent:$version
          docker push ghcr.io/${{ github.repository }}/social-agent:$version
      - name: Retag and push latest Docker image
        run: |
          version=$( cat ./firewheel/model-components/social-agent/version.txt )
          docker tag ghcr.io/${{ github.repository }}/social-agent:$version \
                     ghcr.io/${{ github.repository }}/social-agent:latest 
          docker push ghcr.io/${{ github.repository }}/social-agent:latest
