location /interface {
    proxy_pass http://journal/interface;
}

location /api/ {
    proxy_pass http://gateway;
}

location = /docs {
    proxy_pass http://gateway/docs;
}

location = /healthz {
    proxy_pass http://gateway/healthz;
}

location = /readyz {
    proxy_pass http://gateway/readyz;
}

location = /metrics {
    proxy_pass http://gateway/metrics;
}

location /explorer {
    proxy_pass http://explorer/;
}

location /workbench {
    proxy_pass http://workbench/;
}
